version: '3.9'

services:
  gorp:
    image: myoidc/oidfed-gorp
    volumes:
      - ./config.yaml:/config.yaml
      - ./keys:/keys
      - ./mkcertRootCA.pem:/usr/local/share/ca-certificates/mkcertRootCA.crt:ro
    hostname: gorp.fed3
    networks:
      - default
      - traefik
    labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.gorp-http.rule=Host("gorp.fedservice.lh")
        - traefik.http.routers.gorp-http.entrypoints=http
        - traefik.http.routers.gorp-http.middlewares=https-redirect
        - traefik.http.routers.gorp-https.rule=Host("gorp.fedservice.lh")
        - traefik.http.routers.gorp-https.entrypoints=https
        - traefik.http.routers.gorp-https.tls=true
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.services.gorp.loadbalancer.server.port=3333
    ports:
      - 3333:3333

networks:
  default:
  traefik:
    external: true